/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tonduong.view;

import com.tonduong.database.dao.DJoinroom;
import com.tonduong.database.dao.DRoom;
import com.tonduong.database.pojo.Joinroom;
import com.tonduong.database.pojo.Room;
import com.tonduong.model.struct.UserUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.UUID;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class CreateGroup extends javax.swing.JFrame {

    /**
     * Creates new form Input
     */
    private Home home;

    public CreateGroup(Home h) {
        home = h;
        initComponents();
        handleActions();
        config();
    }

    private void config() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_create = new javax.swing.JButton();


        lb_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_name.setText("Nhập tên nhóm");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancel.setText("Cancel");

        btn_create.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_create.setText("Tạo nhóm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_cancel)
                            .addGap(18, 18, 18)
                            .addComponent(btn_create))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(lb_name))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lb_name)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_create;
    private javax.swing.JLabel lb_name;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
    private JFrame _this = this;

    private void handleActions() {
        btn_cancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                _this.dispose();
            }
        });
        btn_create.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (name.getText().trim().equals("")) {
                    //do nothing
                } else {
                    Room room = new Room(UUID.randomUUID().toString(), UserUI.getIp(), name.getText(), UserUI.getPort());
                    DRoom.add(room);
                    
                    Joinroom joinroom = new Joinroom();
                    joinroom.setIdGroup(room.getId());
                    joinroom.setIdUser(UserUI.getId());
                    DJoinroom.add(joinroom);

                    home.updateHistory(room);
                    _this.dispose();
                }
            }
        });
    }
}
