/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tonduong.view;

import com.tonduong.database.dao.DJoinroom;
import com.tonduong.database.dao.DRoom;
import com.tonduong.database.pojo.Joinroom;
import com.tonduong.database.pojo.Room;
import com.tonduong.model.struct.UserUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class JoinGroup extends javax.swing.JFrame {

    /**
     * Creates new form JoinGroup
     */
    private Home home;
    public JoinGroup(Home h) {
        home = h;
        initComponents();
        lb_notice.setText("");
        config();
        handleActions();
    }

    private void config() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        lb_id = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_join = new javax.swing.JButton();
        lb_notice = new javax.swing.JLabel();


        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_id.setText("Nhập ID của nhóm");

        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancel.setText("Cancel");

        btn_join.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_join.setText("Tham gia");

        lb_notice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_notice.setText("Id của group không tồn tại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_join))
                            .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lb_notice)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lb_id)
                .addGap(18, 18, 18)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_notice)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_join, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_join;
    private javax.swing.JTextField id;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_notice;
    // End of variables declaration//GEN-END:variables
    private JFrame _this = this;

    private void handleActions() {
        btn_cancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                _this.dispose();
            }
        });
        btn_join.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (id.getText().equals("")) {
                    //do nothing
                } else {
                    Room r = DRoom.find(id.getText());
                    if (r != null) {

                        Joinroom j = DJoinroom.findByIdUserAndIdRoom(UserUI.getId(), r.getId());
                        if (j == null) {
                            Joinroom joinroom = new Joinroom();
                            joinroom.setIdGroup(r.getId());
                            joinroom.setIdUser(UserUI.getId());
                            DJoinroom.add(joinroom);
                            home.updateHistory(r);
                            _this.dispose();
                        } else{
                            lb_notice.setText("Bạn đã tham gia group này rồi");
                        }
                    } else {
                        lb_notice.setText("Id group không tồn tại");
                    }
                }
            }
        });
    }
}
