/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tonduong.view;

import com.tonduong.database.dao.DUser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import com.tonduong.database.pojo.User;
import java.util.UUID;

/**
 *
 * @author ADMIN
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        config();
        handleAction();
        lb_notice.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btn_cancel = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lb_password1 = new javax.swing.JLabel();
        repassword = new javax.swing.JPasswordField();
        lb_notice = new javax.swing.JLabel();
        lb_nickname = new javax.swing.JLabel();
        nickname = new javax.swing.JPasswordField();


        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("ĐĂNG KÝ");

        lb_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_username.setText("Tên tài khoản:");

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_password.setText("Mật khẩu:");

        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cancel.setText("Quay lại");

        btn_register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_register.setText("Đăng ký");

        lb_password1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_password1.setText("Nhập lại mật khẩu:");

        lb_notice.setText("Nhập sai vui lòng nhập lại");

        lb_nickname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nickname.setText("Nhập tên người dùng: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lb_password1)
                                .addComponent(lb_username)
                                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(lb_password)
                                .addComponent(password)
                                .addComponent(repassword)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_cancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_register)))
                            .addComponent(lb_nickname)
                            .addComponent(nickname, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lb_notice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(title)
                .addGap(40, 40, 40)
                .addComponent(lb_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lb_notice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_register))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lb_nickname;
    private javax.swing.JLabel lb_notice;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_password1;
    private javax.swing.JLabel lb_username;
    private javax.swing.JPasswordField nickname;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    private JFrame _this = this;
    
    private void config() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private void handleAction() {
        btn_cancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                _this.dispose();
            }
        });
        btn_register.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (username.getText().equals("")
                        || nickname.getText().equals("")
                        || password.getText().equals("")
                        || !repassword.getText().equals(password.getText())) {
                    lb_notice.setText("Nhập sai trường vui lòng nhập lại!!!");
                } else {
                    User user = new User();
                    user.setId(UUID.randomUUID().toString());
                    user.setUsername(username.getText());
                    user.setPassword(password.getText());
                    user.setIp("localhost");
                    user.setNickname(nickname.getText());
                    DUser.add(user);
                    _this.dispose();
                }
            }
        });
    }
}
